name: Publish on PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  test:
    uses: "./.github/workflows/ci.yml"

  deploy:
    name: "Publish to PyPI"
    needs: test  # require tests to pass before deploy runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "poetry"

      - name: Build and publish to PyPI
        run: |
          poetry build
{%- raw %}
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
{%- endraw %}
          poetry publish
