name: Publish on TestPyPI

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "poetry"

      - name: Build and publish to TestPyPI
        run: |
          poetry build
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
{%- raw %}
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
{%- endraw %}
          poetry publish -r test-pypi

