name: Deploy the demo repository

on: [workflow_dispatch, workflow_call]

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout template repo
      uses: actions/checkout@v3
      with:
        path: fair-python-cookiecutter

    - name: Prepare SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        # NOTE: generated private key, stored repo secret
        # (matching public key is registered Deployment Key in target Github repo)
        ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

    - name: Set git author
      run: |
        git config --global user.email "deploy-fair-python-cookiecutter@example.com"
        git config --global user.name "Deployment Bot"

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install poetry
      run: pipx install poetry

    - name: Install cookiecutter
      run: pip install cookiecutter==2.1.1

    - name: Prepare cookiecutter configuration
      run: |
        TEMPLATE_VERSION=$(grep -e "^version" ./fair-python-cookiecutter/pyproject.toml | sed 's/^.*=//')
        echo "extracted template version:" $TEMPLATE_VERSION
        SED_CMD_PREF='s/\(^.*version:\).*/\1'
        SED_CMD="${SED_CMD_PREF}${TEMPLATE_VERSION}/"
        echo "running sed to insert version:" $SED_CMD
        sed "$SED_CMD" ./fair-python-cookiecutter/tests/demo.yaml > cconf.yaml
        echo "resulting repo cookiecutter configuration:"
        cat cconf.yaml

    - name: Instantiate demo repository
      run: cookiecutter ./fair-python-cookiecutter --no-input --config-file=cconf.yaml

    - name: Deploy generated repository
      run: |
        cd fair-python-cookiecutter-demo
        git remote add origin git@github.com:Materials-Data-Science-and-Informatics/fair-python-cookiecutter-demo.git
        git push -f --set-upstream origin main
